#!/bin/sh

mkdir -p .out

build() {
    echo "Building: $1"
    case "$1" in
        cli|client)
            odin build "$1/main.odin" -file -out:.out/"$1.bin" && ./.out/"$1.bin"
            ;;
        server)
            go build -buildvcs=false -o .out/"$1.bin" "$1/main.go"
            ;;
        *)
            echo "	unknown build target '$1'."
            return 1
            ;;
    esac
}

run() {
    echo "Running: $1"
    if [ -f .out/"$1.bin" ]; then
        ./.out/"$1.bin"
    else
        echo "	binary '.out/$1.bin' not found."
        return 1
    fi
}

handle_error() {
    echo "	argument '$1' not found."
}

if [ "$1" = "build" ]; then
    if [ -z "$2" ]; then
        echo "	build target not specified."
        exit 1
    fi
    build "$2"

elif [ "$1" = "run" ]; then
    if [ -z "$2" ]; then
        echo "	run target not specified."
        exit 1
    fi
    run "$2"

elif [ "$1" = "build:run" ]; then
    if [ -z "$2" ]; then
        echo "	build:run target not specified."
        exit 1
    fi
		build "$2"
    run "$2"

elif [ "$1" = "run:build" ]; then
    if [ -z "$2" ]; then
        echo "	run:build target not specified."
        exit 1
    fi
    run "$2"
		build "$2"

elif [ -z "$1" ]; then
    echo "	arguments not found."
else
    handle_error "$1"
fi
